server:
  port: 9150
#Apollo 配置
app:
  id: exploration                              #应用ID
apollo:
  #  cacheDir: /opt/data/                       #配置本地配置缓存目录
  #  cluster: default                           #指定使用哪个集群的配置
#  meta: http://192.168.0.159:8084            #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: application                  #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前
spring:
  application:
    name: exploration-file
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 10000MB
      max-request-size: 10000MB
# 环境不同的配置文件
---
spring:
  config:
    activate:
      on-profile: dev
#  profiles:
#    include:
arthas:
  agent-id: exploration-file-local
---
spring:
  config:
    activate:
      on-profile: test
arthas:
  agent-id: exploration-file