server:
  port: 9150
#Apollo 配置
spring:
  application:
    name: exploration-file
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  servlet:
    multipart:
      enabled: true
      max-file-size: 10000MB
      max-request-size: 10000MB
# 环境不同的配置文件
---
spring:
  config:
    activate:
      on-profile: dev
#  profiles:
#    include:
arthas:
  agent-id: exploration-file-local
---
spring:
  config:
    activate:
      on-profile: test
arthas:
  agent-id: exploration-file