# 模板配置,需要启用,在jar包启动的命令行参数里面加
apollo:
  #  cacheDir: /opt/data/                       #配置本地配置缓存目录
  #  cluster: default                           #指定使用哪个集群的配置
 # meta: http://192.168.0.256:8084            #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: false                            #是否开启 Apollo
    namespaces: application
#    namespaces: TEST1.lan                  #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前
