server:
  port: 9147
spring:
#  config:
#    use-legacy-processing: true
  application:
    name: exploration-gateway
  cloud:
    nacos:
#      discovery:
#        server-addr: 192.168.0.154:8848 #nacos注册中心地址
#        namespace: 111111-11111111-111111111 #对应的namespaceId
      config:
        server-addr: 150.158.195.216:8848 #nacos注册中心地址
        namespace: 0b4cf939-d211-4b0f-83b3-f1bab4b2608d #对应的namespaceId
        group: exploration-gateway #分组ID，这里使用spring.application.name的值
        file-extension: properties
        refresh-enabled: true
        shared-configs:
          - data-id: config.properties #通用配置
            group: exploration-gateway
            refresh: true
    gateway:
      enabled: true
      discovery:
        locator:
          # 启用基于服务发现的路由定位
          enabled: true
          # 启用服务实例id名称小写支持
          lower-case-service-id: true
  profiles:
    active: dev
#      routes:
#  profiles:
#    active: nacos
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# 环境不同的配置文件
---
spring:
  config:
    activate:
      on-profile: dev
#  profiles:
#    include:
arthas:
  agent-id: exploration-gateway-local
---
spring:
  config:
    activate:
      on-profile: prd
arthas:
  agent-id: exploration-gateway