server:
  port: 9147
#  ssl:
#    # 证书在该项目的目录.
#    key-store: cert.p12
#    key-store-password: 123456
#    ## 如下keystoretype可以加上也可以不加
#    key-store-type: PKCS12
#    enabled: true
#  http2:
#    enabled: true
spring:
#  config:
#    use-legacy-processing: true
  application:
    name: exploration-gateway
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          # 启用基于服务发现的路由定位
          enabled: true
          # 启用服务实例id名称小写支持
          lower-case-service-id: true
  profiles:
    active: dev
#      routes:
#  profiles:
#    active: nacos
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
# 环境不同的配置文件
---
spring:
  config:
    activate:
      on-profile: dev
#  profiles:
#    include:
arthas:
  agent-id: exploration-gateway-local
---
spring:
  config:
    activate:
      on-profile: prd
arthas:
  agent-id: exploration-gateway