server:
  port: 9147
spring:
  application:
    name: exploration-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 150.158.195.216:8848 #nacos注册中心地址
        namespace: 740e7864-866b-43b3-bb12-c9f2c29d22a4 #对应的namespaceId
      config:
        server-addr: 192.168.0.149:8848 #nacos注册中心地址
        namespace: 740e7864-866b-43b3-bb12-c9f2c29d22a4 #对应的namespaceId
        group: exploration-gateway #分组ID，这里使用spring.application.name的值
        file-extension: properties
        refresh-enabled: true
        shared-configs:
          - data-id: config.properties #通用配置
            group: exploration-gateway
            refresh: true
          - data-id: db.properties # 数据库配置
            group: exploration-gateway
            refresh: true
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#  profiles:
#    active: nacos
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always