server:
  port: 9148

spring:
  application:
    name: exploration-consumer
  profiles:
    active: dev
# 环境不同的配置文件
---
spring:
  config:
    activate:
      on-profile: dev
#  profiles:
#    include:
arthas:
  agent-id: exploration-consumer-local
---
spring:
  config:
    activate:
      on-profile: prd
arthas:
  agent-id: exploration-consumer