server:
  port: 9148
#Apollo 配置
app:
  id: exploration                              #应用ID
apollo:
  #  cacheDir: /opt/data/                       #配置本地配置缓存目录
  #  cluster: default                           #指定使用哪个集群的配置
 # meta: http://192.168.0.256:8084            #DEV环境配置中心地址
  autoUpdateInjectedSpringProperties: true   #是否开启 Spring 参数自动更新
  bootstrap:
    enabled: true                            #是否开启 Apollo
    namespaces: application
#    namespaces: TEST1.lan                  #设置 Namespace
    eagerLoad:
      enabled: false                         #将 Apollo 加载提到初始化日志系统之前
spring:
  application:
    name: exploration-consumer
  profiles:
    active: dev
# 环境不同的配置文件
---
spring:
  config:
    activate:
      on-profile: dev
#  profiles:
#    include:
arthas:
  agent-id: exploration-consumer-local
---
spring:
  config:
    activate:
      on-profile: prd
arthas:
  agent-id: exploration-consumer