server:
  port: 9148

spring:
  application:
    name: exploration-consumer
  profiles:
    active: dev
dubbo:
  # 配置服务信息
  application:
    name: dubbo-consumer-consumer
    # 禁用QOS同一台机器可能会有端口冲突现象
    qos-enable: false
    qos-accept-foreign-ip: false
  # 配置注册中心
  registry:
#    address: nacos://150.158.195.216:8848?namespace=8f9b5fab-0e49-4e90-a07e-c93bd1bcaed7
  # 设置超时时间
  consumer:
    timeout: 4000

# 环境不同的配置文件
---
spring:
  config:
    activate:
      on-profile: dev
#  profiles:
#    include:
arthas:
  agent-id: exploration-consumer-local
---
spring:
  config:
    activate:
      on-profile: prd
arthas:
  agent-id: exploration-consumer